-- 0007 — what the user asked for, kept beside what yt-dlp answered (`T-159`, `REQ-009`).
--
-- **A history row said `251`.** That is yt-dlp's format id for YouTube's Opus audio stream, and a
-- merged download said `399+140` — two ids joined by yt-dlp's own selector syntax. So the field a
-- user reads to answer *what did I get* answered with an internal join expression, with no
-- explanation available anywhere in the window.
--
-- **The column this adds is the *request*, not a nicer string**, and the reason is `T140-R3`'s.
-- That finding was the queue header showing `bestvideo+bestaudio/best` where its own control
-- offered *Best video available*; the fix routed it through a function that prefers a preset's
-- name and falls back to the literal — and that function reads the **request**, never the chosen
-- preset, because the request is what the worker was given. History could not use it: the record
-- carried `format_used` and nothing else, and `audio_quality` is preset-owned, so a download
-- converted at 320 kbps cannot be matched to a preset without the request that named it.
--
-- Storing the resolved *name* instead was rejected. It is a derived value with a lifetime — a
-- preset renamed in a later build would leave every old record asserting a name this application
-- no longer has — and it would be a second opinion about a download beside the one the queue
-- forms. One serialisation, one naming rule, three surfaces.
--
-- The same JSON `jobs.request` holds, written by the same serializer, so a history row and the job
-- row it came from cannot disagree about what was asked for.
--
-- Nullable, no default, no backfill, for `0002` through `0006`'s reason: a record written before
-- this ran never had a request stored, and there is nothing to reconstruct one from. Those rows
-- keep saying what yt-dlp reported, through `_text_or_absent`'s existing rule — honest about being
-- an id rather than dressed up as a name that was never recorded.
--
-- Forward-only. One `ALTER TABLE ... ADD COLUMN`, which SQLite applies without rewriting.

ALTER TABLE history ADD COLUMN request TEXT;
