-- 0009 — the completion record is purged, not merely orphaned (`T169-R3`, `REQ-020`).
--
-- **This is the only destructive migration in the project, and it is destructive on purpose.**
-- `T-169` and `T-170` withdrew the completion ledger and deleted every path that reads or writes
-- it, but `0008` left the table populated. `T169-R3` measured what that means for someone who
-- upgrades rather than installs fresh: opening the frozen v7 database on the withdrawal head kept
-- all three of its rows — source URLs and output paths included — with no route in the application
-- to see or clear them. `REQ-020` says the application keeps no record of what has been
-- downloaded. Those rows are exactly that record, so the contract and the database disagreed, and
-- the database was the one telling the truth.
--
-- **The maintainer ruled to purge**, 2026-08-06, choosing it over keeping a bounded clearing route
-- and over preserving the rows behind an amended contract. `DAT-006`'s legacy-data note records the
-- ruling and the two rejected options. **An implementer must not infer a deletion of a user's data
-- from a UI removal** — that is `T169-R1`'s authority lesson, and it is why this file waited for a
-- ruling instead of shipping with the withdrawal.
--
-- **`DAT-006` §5 does not apply, and the distinction is worth stating.** §5 refused a *column* drop
-- because SQLite implements one as a table rebuild: a rewrite of every row in order to keep every
-- row, where an interruption risks the data the rewrite exists to preserve. Nothing here preserves
-- anything. `DROP TABLE` unlinks the table and its indexes — no row is copied, so there is no
-- half-copied state to be interrupted in, and the risk §5 weighed against a tidiness benefit is
-- not present when removal is the benefit.
--
-- **`secure_delete` is set here on purpose, and it is not decoration** (`T169-R6`). Without it
-- SQLite moves the dropped pages to the freelist *without zeroing them*, so every purged URL stays
-- legible in the file until something happens to overwrite it. With it, they are zeroed as the
-- pages are freed — measured at 200 occurrences before and 0 after.
--
-- **The reason it is set explicitly is that the default is not ours to rely on.** It is a compile
-- option: the Fedora build this was written on has `SQLITE_SECURE_DELETE` on, so the drop already
-- zeroed without asking, while a Windows Python or a bundled SQLite may well default off. Leaving
-- it implicit makes the erasure a property of whoever built the library rather than of this
-- migration, and the same upgrade would then behave differently on two of a user's machines.
--
-- **It is deliberately not restored afterwards.** There is no way to capture and put back the prior
-- value in pure SQL, so restoring would mean writing `OFF` — which on a build like the one above
-- would leave the connection *less* safe than it was found. The cost of leaving it on is bounded to
-- nothing: `migrate` only runs a script for a version above the database's own, so this executes on
-- the single connection performing the single upgrade, and never again.
--
-- **What this still cannot promise.** In WAL mode the old content also lives in the `-wal` sidecar
-- until a checkpoint retires it, and a hard exit before that leaves it there. `secure_delete` does
-- not reach it and neither can this script: `VACUUM` cannot run in a transaction, and this one runs
-- inside the transaction carrying its version bump. So a user who wants no trace should delete the
-- database **together with its `-wal` and `-shm` siblings** — deleting `library.sqlite3` alone can
-- leave a `library.sqlite3-wal` holding exactly what they meant to remove.
--
-- **The pragma was added after this migration first shipped, and that has one consequence.**
-- `migrate` runs a script only for a version above the database's own, so a database that already
-- reached v9 before this edit will never execute this file again: its dropped pages keep whatever
-- zeroing its SQLite build happened to do, and the correction does not reach it. That is
-- acceptable here only because nothing is released — no tag, no installer — so the population is a
-- developer's own database. It would not be acceptable after a release, where editing a shipped
-- migration silently divides users into those who ran the old text and those who ran the new, and
-- the fix would have to be `0010`.
--
-- **Irreversible, like every migration here.** Forward-only (`T-014`): there is no down-migration
-- to restore the table, and restoring a backup is the honest recovery path. Unlike the other eight,
-- this one has something to recover.
--
-- The `history_completed_at` and `history_normalised_url` indexes are not dropped separately —
-- SQLite drops a table's indexes with it, and naming them would only invite a later reader to
-- wonder which of the two statements did the work.

PRAGMA secure_delete = ON;

DROP TABLE history;
