"""Generate the option table the escape hatch decides from (`T-184`, `REQ-031`).

**Why a generated module rather than reading the audit at runtime.** `docs/YTDLP_OPTION_AUDIT.md`
is the authority for what each yt-dlp option is and why, and the product has to carry two things
out of it: which options a user may type, and **the stated reason** a refused one is refused —
`REQ-031` requires the refusal to name the reason rather than say "not permitted". A markdown file
in `docs/` is not shipped in the wheel and parsing prose at runtime would put the boundary's
correctness in a regular expression evaluated on a user's machine.

So this writes a Python module, and `tests/unit/test_option_table.py` compares the two **in both
directions** — the same arrangement `persistence/schema.sql` already has with its migrations. A
row edited in the audit and not regenerated here fails; a row invented here and absent from the
audit fails too.

    python tools/ytdlp_option_table.py            # rewrite the module
    python tools/ytdlp_option_table.py --check    # exit 1 if it is out of date

**Nothing here is policy.** Every class and every reason is the audit's, copied. The decision of
what to do with each class is `downloader/extra_options.py`'s, and the ruling behind it — that the
hatch is **default-deny** — is the maintainer's, taken 2026-09-18.
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path
from typing import Final

ROOT: Final = Path(__file__).resolve().parent.parent
AUDIT: Final = ROOT / "docs" / "YTDLP_OPTION_AUDIT.md"
TARGET: Final = ROOT / "src" / "tracks_and_trails" / "downloader" / "option_table.py"

#: The audit's own row shape: one or more backtick-quoted spellings, a class, a reason.
_ROW: Final = re.compile(r"^\|((?:\s*`[^`]+`)+)\s*\|\s*`([a-z:]+)`\s*\|\s*(.+?)\s*\|$")

_HEADER: Final = '''"""Every documented yt-dlp option, its class and its reason. **Generated.**

Do not edit this file. It is written by `tools/ytdlp_option_table.py` from
`docs/YTDLP_OPTION_AUDIT.md`, which is the authority, and
`tests/unit/test_option_table.py` compares the two in both directions.

Re-run the generator when the audit changes:

    python tools/ytdlp_option_table.py

`T-184` consumes this; `T-183` produced the classification it carries.
"""

from __future__ import annotations

from typing import Final

#: The yt-dlp release the audit was taken against. `tests/unit/test_option_audit.py` fails when
#: the pin moves, because a bump is exactly when the classification has to be looked at again.
AUDIT_VERSION: Final = "{version}"

#: Spelling -> (class, the audit's reason). **Every** spelling of an option is a key, so a lookup
#: is by the string the user actually typed and no caller has to know which spellings are aliases.
OPTION_CLASSES: Final[dict[str, tuple[str, str]]] = {{
{rows}}}

#: The typed options that already have a control, spelling -> the `DownloadRequest` field.
#:
#: `ARC-010` gives the visible control the win where both name the same user-owned key, so these
#: are **refused** through the hatch and pointed at their control. A typed option that is still
#: waiting for its task is permitted, and only this table tells the two apart.
TYPED_WITH_A_FIELD: Final[dict[str, str]] = {{
{built}}}

#: Every spelling the parser knows, and how many values it consumes.
#:
#: **Pinned rather than asked at runtime.** `tests/unit/test_layering.py` confines `yt_dlp` imports
#: to `worker.py` and `ytdlp_adapter.py` so upstream churn stays absorbable (`NFR-008`), and the
#: hatch has to decide what a user typed before anything is parsed. It covers suppressed options
#: too: they are known spellings with no ruling, which is a different answer from "no such option".
OPTION_ARITY: Final[dict[str, int]] = {{
{arity}}}
'''


def audit_rows() -> list[tuple[tuple[str, ...], str, str]]:
    """The classification tables only. The findings above them have tables of their own."""
    text = AUDIT.read_text(encoding="utf-8")
    _, _, tables = text.partition("\n## The tables\n")
    if not tables:
        raise SystemExit("the audit has no '## The tables' section to read")
    found = []
    for line in tables.splitlines():
        match = _ROW.match(line.strip())
        if match:
            spellings = tuple(re.findall(r"`([^`]+)`", match.group(1)))
            found.append((spellings, match.group(2), match.group(3)))
    return found


def built_typed_options() -> dict[str, str]:
    """The typed options that already have a `DownloadRequest` field, read from the audit.

    **Stated rather than inferred**, which is `T183-R4`'s correction: deriving "built" from what
    the nine typed tasks did not claim is circular, and swapping a built option for an unbuilt one
    kept every count intact. The hatch needs this because a typed option **with** a control is
    refused — `ARC-010` gives the visible control the win — while one still waiting for its task is
    permitted, and only this table separates them.
    """
    text = AUDIT.read_text(encoding="utf-8")
    header = text.index("| Option | `DownloadRequest` field |")
    table = text[header : text.index("\n\n", header)]
    return {
        found.group(1): found.group(2)
        for line in table.split("\n")[2:]
        if (found := re.match(r"^\| `([^`]+)` \| `([^`]+)` \|$", line.strip()))
    }


def parser_arity() -> dict[str, int]:
    """Every spelling yt-dlp's parser knows, and how many values each consumes.

    **Generated rather than read at runtime**, and that is an architecture rule rather than a
    preference: `tests/unit/test_layering.py` confines `yt_dlp` imports to `worker.py` and
    `ytdlp_adapter.py`, so upstream churn stays absorbable (`NFR-008`). Pinning the table here
    means the hatch can decide what a user typed **without importing yt-dlp at all**, and the
    version test fails if the installed release ever stops matching the pin.

    `create_parser()` builds the option table and returns; none of `parse_options`' side effects
    happen, which is what makes this safe to run at all.
    """
    from yt_dlp.options import create_parser

    parser = create_parser()
    arity: dict[str, int] = {}
    for group in parser.option_groups:
        for option in group.option_list:
            takes = option.nargs if option.takes_value() else 0
            for spelling in tuple(option._short_opts) + tuple(option._long_opts):
                arity[spelling] = takes or 0
    return arity


def audit_version() -> str:
    stated = re.search(r"\*\*yt-dlp version:\*\* \*\*([0-9.]+)\*\*", AUDIT.read_text("utf-8"))
    if stated is None:
        raise SystemExit("the audit does not state the yt-dlp version it was taken against")
    return stated.group(1)


#: Ruff's limit for this repository. The generated file goes through the same gates as anything
#: written by hand, so an entry that would overrun it is wrapped here rather than excused there.
_WIDTH: Final = 100


def _entry(spelling: str, group: str, reason: str) -> str:
    """One `"spelling": ("class", "reason"),` line, wrapped when it will not fit.

    The audit's longest reason is over 200 characters, and no formatter splits a string literal,
    so a long one is emitted as implicit concatenation. `ruff format` leaves those alone, which is
    what makes the generated file stable under `--check`.
    """
    flat = f"    {spelling!r}: ({group!r}, {reason!r}),"
    if len(flat) <= _WIDTH:
        return flat + "\n"

    room = _WIDTH - 8 - 3  # eight spaces of indent, two quotes and a trailing space
    chunks: list[str] = []
    rest = reason
    while len(rest) > room:
        cut = rest.rfind(" ", 0, room)
        cut = cut if cut > 0 else room
        chunks.append(rest[: cut + 1])
        rest = rest[cut + 1 :]
    chunks.append(rest)

    body = "".join(f"        {chunk!r}\n" for chunk in chunks)
    return f"    {spelling!r}: (\n        {group!r},\n{body}    ),\n"


def rendered() -> str:
    """The module text, with one entry per spelling rather than per row."""
    lines = []
    for spellings, group, reason in sorted(audit_rows()):
        for spelling in spellings:
            lines.append(_entry(spelling, group, reason))
    built = "".join(
        f"    {spelling!r}: {field!r},\n"
        for spelling, field in sorted(built_typed_options().items())
    )
    arity = "".join(
        f"    {spelling!r}: {takes!r},\n" for spelling, takes in sorted(parser_arity().items())
    )
    return _formatted(
        _HEADER.format(version=audit_version(), rows="".join(lines), built=built, arity=arity)
    )


def _formatted(text: str) -> str:
    """`text` as `ruff format` would write it, so the gate and the generator cannot disagree."""
    formatted = subprocess.run(  # noqa: S603 - a fixed argv, and ruff is this repo's formatter
        [sys.executable, "-m", "ruff", "format", "--stdin-filename", str(TARGET), "-"],
        input=text,
        capture_output=True,
        text=True,
        check=False,
    )
    if formatted.returncode != 0:
        raise SystemExit(f"ruff format refused the generated module:\n{formatted.stderr}")
    return formatted.stdout


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--check",
        action="store_true",
        help="say whether the module is up to date rather than rewriting it",
    )
    arguments = parser.parse_args()

    wanted = rendered()
    if arguments.check:
        current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else ""
        if current == wanted:
            print(f"{TARGET.relative_to(ROOT)} is up to date")
            return 0
        print(f"{TARGET.relative_to(ROOT)} is out of date; run this tool without --check")
        return 1

    TARGET.write_text(wanted, encoding="utf-8")
    entries = len(audit_rows())
    print(f"wrote {TARGET.relative_to(ROOT)} from {entries} audit rows")
    return 0


if __name__ == "__main__":
    sys.exit(main())
